README.md

docs: create `README.md`

---

build.gradle

- Indentation rules were added to be in-line with `.editorconfig`
```gradle
trimTrailingWhitespace()
indentWithSpaces()
endWithNewline()
```
- Tab indentation in `build.gradle` were replaced with 4 whitespaces

refactor: indent from tab to whitespace

---

build.gradle
src/main/java/pls_no_shinobu/videostore/HelloApplication.java
src/main/java/pls_no_shinobu/videostore/HelloController.java

- Remove acknowledgement line from header (`Acknowledgement: Acknowledge the resources that you use here.`)

build: remove acknowledgement from header

---

.github/workflows/build.yml
.github/workflows/test.yml

- Removed `macos-latest` from test platform

build(ci): remove macos-latest from workflow platform

---

data/customers.txt
data/items.txt
src/main/java/pls_no_shinobu/videostore/model/Entity.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/utils/CoreUtils.java
src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
src/test/java/pls_no_shinobu/videostore/model/TestItem.java
src/test/java/pls_no_shinobu/videostore/utils/TestItemUtils.java

- Added demo data (`customers.txt` and `items.txt`) - this later needed to implement a csv parser
- Changed `Entity` class to abstract as it won't be use for creating new object
- Changed `genres` in `Item` class to single `String genre`
- Changed `Item` test to reflect the genres changes
- Introduced `CoreUtils` abstract with parser and serialize
- Implemented `ItemUtils` for parsing items and serializing them
- Implemented tests for `ItemUtils`

feat: implement `CoreUtils` with `ItemUtils` csv parser

---

src/main/java/pls_no_shinobu/videostore/model/User.java

- Implemented `User` class with some basic utilities

feat: implement `User` class

---

src/main/java/pls_no_shinobu/videostore/model/User.java
src/test/java/pls_no_shinobu/videostore/model/TestItem.java
src/test/java/pls_no_shinobu/videostore/model/TestUser.java

- Implemented `User` class tests, with test for `id`, `username`, `password` and rentals-related
- Fixed `User` constructor not throwing error and password check are failing
- Fixed `private ArrayList<String> rentals` not being initiated
- Changed `Item` test display name

test: implement `User` class tests

---

src/main/java/pls_no_shinobu/videostore/model/User.java
src/test/java/pls_no_shinobu/videostore/model/TestUser.java

- Implemented check for `User`'s setter methods - such as compare with previous value to throw an "Unchanged" exception
- Changed `addRental()` test to add an `Item` instead of itemID

fix: implemented check for `User`'s setter methods

---

src/main/java/pls_no_shinobu/videostore/drivers/PasswordHasher.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/test/java/pls_no_shinobu/videostore/drivers/TestPasswordHasher.java

- Implemented password hashing using PBKDF2
- Implemented hashing password for creating new password on class `User`
- Implemented password check on class `User`
- Introduced tests for password hashing

feat: implement password hasher & hash the password for `User` class

---

.github/workflows/build.yml
.github/workflows/test.yml
.idea/misc.xml
build.gradle

- Changed Java compatibility (and JDK) version from 19 to 17

build: lower java compatibility version

---

src/main/java/pls_no_shinobu/videostore/errors/DuplicateException.java
src/main/java/pls_no_shinobu/videostore/manager/Manager.java
src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
src/test/java/pls_no_shinobu/videostore/manager/UserManagerTest.java

- Implemented `Manager` abstract class for building `Entity` managers
- Implemented `UserManager` as the first manager for `User` - as storing users, closes #30, #29, #28 
- Introduced test cases for `UserManager`

feat: implemented `Manager` abstract class with `UserManager` and test cases

---

src/main/java/pls_no_shinobu/videostore/manager/Manager.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/test/java/pls_no_shinobu/videostore/model/TestItem.java
src/test/java/pls_no_shinobu/videostore/model/TestUser.java

- Redone `Item`, `User` and `Manager` constructor
- Removed unused code from tests

fix: redone constructors and removed unused code

---

src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
src/main/java/pls_no_shinobu/videostore/model/Transaction.java
src/test/java/pls_no_shinobu/videostore/manager/TestUserManager.java

- Written docs for `Transaction` class
- Introduced more feature to `Transaction`, including setters and checks for `setResolved()`
- Implemented `ArrayList` constructor for `UserManager`
- Renamed `UserManagerTest` to `TestUserManager`

feat: introduce more feature to `Transaction` and a constructor for `UserManager`

---

src/main/java/pls_no_shinobu/videostore/errors/ManagerLimitException.java
src/main/java/pls_no_shinobu/videostore/manager/AbstractManager.java
src/main/java/pls_no_shinobu/videostore/manager/Manager.java
src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
src/main/java/pls_no_shinobu/videostore/model/Entity.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/main/java/pls_no_shinobu/videostore/utils/CSVUtils.java
src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
src/test/java/pls_no_shinobu/videostore/manager/TestUserManager.java
src/test/java/pls_no_shinobu/videostore/model/TestItem.java

- Introduced `Manager` interface and abstract class for building - e.g. `UserManager`, `ItemManager` and `TransactionManager`.
- Implemented `getUnusedID()` from `Manager` interface for `UserManager`
- Updated the docs for `Entity`, `Item` and `User`
- Updated test for `Item`

feat: `Manager` implementations, a lot of refactoring and doc updates

---

src/main/java/pls_no_shinobu/videostore/errors/ManagerLimitException.java
src/main/java/pls_no_shinobu/videostore/manager/AbstractManager.java
src/main/java/pls_no_shinobu/videostore/manager/Manager.java
src/main/java/pls_no_shinobu/videostore/manager/TransactionManager.java
src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
src/main/java/pls_no_shinobu/videostore/model/Entity.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/model/Transaction.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/main/java/pls_no_shinobu/videostore/utils/CSVUtils.java
src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
src/test/java/pls_no_shinobu/videostore/manager/TestUserManager.java
src/test/java/pls_no_shinobu/videostore/model/TestItem.java

- Implemented `TransactionManager`

feat: implement `TransactionManager`

---

src/main/java/pls_no_shinobu/videostore/manager/TransactionManager.java

- Implemented `find` method for `TransactionManager`

feat: add find method for `TransactionManager`

---

src/main/java/pls_no_shinobu/videostore/model/User.java
src/test/java/pls_no_shinobu/videostore/model/TestUser.java

- Changed how `User` store rentals: now with `ArrayList<Item>`
- Removed rentals-related tests for `User`

feat: change how `User` store rentals (replace `Transaction` with `Item`)

---

src/main/java/pls_no_shinobu/videostore/manager/UserManager.java

- Updated `Entity` link in `UserManager`

docs: update JavaDoc `Entity` link

---

src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/utils/ItemUtils.java
src/test/java/pls_no_shinobu/videostore/utils/TestItemUtils.java

- Implemented serialize for saving `Item` to CSV-compatible file
- Added docs for `ItemUtils`
- Added `serialize` test for `ItemUtils`

feat: implement serialize and add docs for `ItemUtils`, with updated test

---

build.gradle
src/main/java/pls_no_shinobu/videostore/VideoStoreApplication.java
src/main/java/pls_no_shinobu/videostore/controller/SignInController.java
src/main/java/pls_no_shinobu/videostore/controller/SignUpController.java
src/main/java/pls_no_shinobu/videostore/controller/utils/SceneUtils.java
src/main/java/pls_no_shinobu/videostore/core/CSVDatabase.java
src/main/java/pls_no_shinobu/videostore/core/Database.java
src/main/java/pls_no_shinobu/videostore/core/Session.java
src/main/java/pls_no_shinobu/videostore/errors/IncorrectLoginInfo.java
src/main/java/pls_no_shinobu/videostore/manager/UserManager.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/main/resources/pls_no_shinobu/videostore/signin.fxml
src/main/resources/pls_no_shinobu/videostore/signup.fxml

- Renamed application from `HelloApplication` to `VideoStoreApplication`
- Implemented `Database` interface with `CSVDatabase` class
- Added ability to get a `User` object from manager using username
- Added docs for `Item` `getYear()`
- Fixed missing `rentalCount` and `userType` on `User` minimal constructor
- Implemented Sign-in/Sign-up on GUI using `CSVDatabase` and `Session` singletons

feat: changing application name, implemented `Database` and `Session` singleton

---

src/main/java/module-info.java
src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
src/main/java/pls_no_shinobu/videostore/model/Item.java
src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml

- Implemented data fetch on all `TableView` on userDashboard & adminDashboard
- Implemented changing user name, address and phone on profile

feat: finish implementing GUI features

---

data/items.csv
data/users.csv
src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
src/main/java/pls_no_shinobu/videostore/model/User.java
src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml
src/test/java/pls_no_shinobu/videostore/utils/TestFileIOUtils.java

- Updated data file with hashed password and admin account.
- Implemented ability to return a rental without `TransactionManager`
- Updated test to reflect the changed default data file
- Implemented rent and return features on `userDashboard` GUI

feat: implement GUI rent & return features

---

src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
src/main/resources/pls_no_shinobu/videostore/adminDashboard.fxml
src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml

- Implemented search functions for both User Dashboard and Admin Dashboard
- Implemented sort function on user screen in Admin Dashboard

feat: implement search and sort functions

---

src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java

- Fixed dialog showing "success" message even when there are errors
- Extracted method outside lambda functions

fix: extract methods & "fake success" dialogs

---

src/main/java/pls_no_shinobu/videostore/controller/AdminDashboardController.java
src/main/java/pls_no_shinobu/videostore/controller/UserDashboardController.java
src/main/java/pls_no_shinobu/videostore/controller/utils/PaneUtils.java
src/main/resources/pls_no_shinobu/videostore/userDashboard.fxml

- Add a transition for 'setPane' method
- Add a filter for sorting item's rental type
- Add 'ALL' option to the user's role filter and make it compatible with the searching function
- Align table columns to center left
- Minor UI changes for the 'Help' button

feat: add new filters for dashboards

---

doc/README.md

Please look at the changes and see if there's any question. Thank you.

docs: update contributions info

---

doc/README.md

I believe Khoa deserves more recognition and Catou need to be credited more. If you have any problem, contact me and I will deal it myself, I believe this is the best contributions for this project

docs: changes in contribution
